<!DOCTYPE html>
<html lang="en">
<head>
  <title>Hospital Management Software</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="dist/css/bootstrap.min.css">
  <script src="jquery-3.1.0.min.js"></script>
  <script src="dist/js/bootstrap.min.js"></script>
<style type="text/css">
	#size
	{
	width:100px;
	height:150px;
	}
	.form-signin
	{
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
    }
	.form-signin .form-signin-heading,
    .form-signin .checkbox
	{
     margin-bottom: 10px;
    }
   .form-signin .checkbox
   {
    font-weight: normal;
   }

   .form-signin .form-control
   {
    position: relative;
    height: auto;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    padding: 10px;
    font-size: 16px;
   }
   .form-signin .form-control:focus
   {
    z-index: 2;
   }
	</style>
</head>
  <body class="container">
